# Generated by Django 5.1.1 on 2024-10-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
    ]
